spring:
  application:
    name: "vom-server"

  profiles:
    active: "dev"

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:file:~/.vom/env"
    username: "sa"
    password: ""


---
collector:
  datasource:
    driver-class-name: "org.h2.Driver"
    jdbc-url: "jdbc:h2:mem:collector"
    username: "sa"
    password: ""


server:
  port: 8888
